# Generated by Django 4.2.2 on 2023-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_create_at_product_discount_product_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flag',
        ),
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
