# Generated by Django 4.2.2 on 2023-08-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
